import { ApolloWrapper } from "@/lib/apollo-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "@/lib/chakra";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <Providers>
            <main className="subpixel-antialiased relative mx-auto flex min-h-screen h-screen overflow-hidden scroll-bar-hide justify-center bg-[#1A1B1E] text-gray-300">
              <div className="w-full flex flex-row ">
                <div
                  id="scrollableDiv"
                  className="flex flex-col p-2 md:px-8 md:pt-6  w-full overflow-y-auto h-full dark-scroll-bar"
                >
                  {children}
                </div>
              </div>
            </main>
          </Providers>
        </ApolloWrapper>
      </body>
    </html>
  );
}
